### ISSUE TITLE
Selecting checkbox on child row, toggles the row and shows parent row

### ISSUE THREAD

**Issue by sherylj** [reactabular/treetabular#14]
Hi,

So far, I've been able to use the functionalities of reactabular and it's components for my use case.
Thanks for Reactabular!

I noticed this issue when I added a select check box for each row (parent and child).
When I try to select the checkbox of the child, it removes the row and displays the parent. 
And if the parent's checkbox is selected and is expanded to show the child, unselecting the parent's checkbox, closes the child row.
How can I disable the toggle if I select the checkbox?

I used the below onRow code (after seeing this reactabular (https://github.com/reactabular/reactabular/issues/242) 
```
onRow(row, { rowIndex }) {
    return {
      className: classnames(
        rowIndex % 2 ? 'odd-row' : 'even-row',
        row.selected && 'selected-row'
      ),
      onClick: (e) => this.onSelectRow(e, row, rowIndex)
    };
  }
  onSelectRow({ target: {tagName}}, row, selectedRowIndex) {
    console.log('selected row' + tagName);
    if (tagName === 'INPUT') {
      this.props.onHandleSelect(row);
    } else {
      const { rows } = this.state;
      const selectedRowId = rows[selectedRowIndex].id;
      this.setState(
          compose(
            select.rows(r => r.selected === selectedRowId),
            select.none
          )(rows)
        );
    }
  }
```
![screen shot 2017-04-03 at 3 54 26 pm](https://cloud.githubusercontent.com/assets/1127458/24635166/c2ebb992-1886-11e7-964c-cbe4f8774f89.png)

**Comment by bebraw** [comment]
Can you set up a small standalone example I can run to study?

**Comment by sherylj** [comment]
Thanks @bebraw 
Sorry, I'm caught up with a deadline. But, I'll try setting up a standalone project for the above issue and have it ready in a few days.

**Comment by bebraw** [comment]
It's alright. Take care. I have a feeling it's something state related.

**Comment by pzmudzinski** [comment]
any news on that?

**Comment by sherylj** [comment]
Hi, Sorry for the delay. I found my error.
Bebraw is right, I had updated the state when selecting the option and that re-rendered the table. So, that's the reason why it was displaying the parent again. This works fine now.
Thanks
