### ISSUE TITLE
Is there support for multiple parents?

### ISSUE THREAD

**Issue by vijayst** [reactabular/treetabular#6]
Is there support for multiple parents? In my app, the child node needs to be present in multiple places (parents). Is that possible now? Thanks.

**Comment by bebraw** [comment]
The only way I can see is duplicating those child nodes and then handling the identity problem elsewhere if you have to do edits.

Having some kind of support for references and resolving those might be interesting though I have a feeling the resolution problem could be handled with [table-resolver](https://github.com/reactabular/table-resolver). It depends a lot on the structure you are dealing with currently.

**Comment by vijayst** [comment]
Thanks @bebraw. There is no edit. A read-only table with multiple parents.

**Comment by bebraw** [comment]
Ok. Duplicating the children should be enough then.
