### ISSUE TITLE
parentId as default value for idField in the documentation.

### ISSUE THREAD

**Issue by vijayst** [reactabular/treetabular#7]
Some of the methods use default value of 'parentId' for the idField in the docs. For example, filter method is shown below:
```
tree.filter = ({ fieldName, idField = 'parentId', parentField = 'parent' }) => (rows) => [<filteredRow>] 
```
I have not supplied a non-default idField of 'id'. Is it an error with the documentation? Or should I specify a non-default idField - in my case, it is 'id'? Thanks.

**Comment by bebraw** [comment]
Fixed the documentation. Thanks.
