### ISSUE TITLE
Treetabular not working correctly for 'undefined' parents.

### ISSUE THREAD

**Issue by vijayst** [reactabular/treetabular#9]
There is a minor bug in the getParents utility. This line expects the parent field to be null. If the parent is undefined, the tree does not work correctly.

```
if ((cell[parentField] === null) || (typeof cell[parentField] === 'undefined')) {
        break;
 }
```
With the second OR clause added, the tree expands correctly.

**Comment by bebraw** [comment]
Can you PR? Add a test against this case too.

**Comment by vijayst** [comment]
Sure, thanks.

**Comment by bebraw** [comment]
Fixed.
